[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build]
  command = "yarn run build"
  publish = ".next"

[functions]
  included_files = [
    "./public/**"
  ]

  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
